#
# Copyright (c) 2022-2023 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.7'

networks:
  edgex_edgex-network:
    external: true
    driver: "bridge"

services:
  edgex-app-camera-management:
    image: edgexfoundry/app-camera-management:0.0.0-dev
    hostname: edgex-app-camera-management
    container_name: edgex-app-camera-management
    networks:
      - edgex_edgex-network
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-app-camera-management
      SERVICE_SERVERBINDADDR: "0.0.0.0"
      APPCUSTOM_EVAMBASEURL: "http://edgex-video-analytics:8080"
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    depends_on:
      edgex-video-analytics:
        condition: service_started
    ports:
      - '59750:59750/tcp'

  edgex-video-analytics:
    image: intel/edge_video_analytics_microservice:0.7.2
    hostname: edgex-video-analytics
    container_name: edgex-video-analytics
    privileged: true
    entrypoint: ["./run.sh"]
    ports:
      - '8080:8080'
      - '8555:8555'
    networks:
      - edgex_edgex-network
    environment:
      ENABLE_RTSP: "true"
      RTSP_PORT: 8555
      RUN_MODE: EVA
      ENABLE_WEBRTC: "false"
      WEBRTC_SIGNALING_SERVER: ws://localhost:8443
      # Default Detection and Classification Device
      DETECTION_DEVICE: CPU
      CLASSIFICATION_DEVICE: CPU
      GST_DEBUG: "*:2,python*:4"
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - "./edge-video-analytics/pipelines/:/home/pipeline-server/pipelines/"
      - "./edge-video-analytics/models:/home/pipeline-server/models/"
      - "./edge-video-analytics/config.json:/home/pipeline-server/config.json"
    device_cgroup_rules:
      # Default run - device-cgroup-rule='c 189:* rmw'
      # NCS2 run - device-cgroup-rule='c 209:* rmw'
      # Selective rules can be applied for deployment
      - 'c 189:* rmw'
      - 'c 209:* rmw'
    devices:
      # Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
      # ion - VPU
      # USB camera devices
      # Selective mount can be done for deployment as mounting whole /dev is not recommended
      - "/dev:/dev"
