[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'AWS IoT Export Service'
Timeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.edgex-core-data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

[Trigger]
Type="edgex-messagebus"
SubscribeTopics="edgex/events/#"
  [Trigger.EdgexMessageBus]
  Type = "redisstreams"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"

[ApplicationSettings]
AwsIoTMQTTHost      = "***.iot.us-west-2.amazonaws.com"
AwsIoTMQTTPort      = "8883"
awsIoTThingName     = "testThing"
MQTTCert            = "./certs/user.client.crt"
MQTTKey             = "./certs/user.client.key"
SkipCertVerify	    = "false"
PersistOnError	    = "false"
topic               = "$aws/things/testThing/shadow/update"
AwsDeviceNames      = ""
