[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Azure IoT Export Service'
Timeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.edgex-core-data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

[Trigger]
Type="edgex-messagebus"
SubscribeTopics="edgex/events/#"
  [Trigger.EdgexMessageBus]
  Type = "redisstreams"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"

[ApplicationSettings]
IoTHub         = "EdgeX"
IoTDevice      = "MyDevice"
MQTTCert       = "/secret/rsa_cert.pem"
MQTTKey        = "/secret/rsa_private.pem"
TokenPath      = "/vault/config/assets/resp-init.json"
VaultHost      = "localhost"
VaultPort      = "8200"
CertPath       = "v1/secret/edgex/pki/tls/azure"
DeviceNames    = "Random-Integer-Generator01"

[MqttSecretConfig]
BrokerAddress = "tcp://broker.hivemq.com:1883"
ClientId = "azure-export"
AutoReconnect = true
Topic = "edgex-export"
AuthMode = "none"