[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = "30s"
CheckInterval = "10s"
Host = "localhost"
ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
Port = 50001
Protocol = "http"
ReadMaxLimit = 100
StartupMsg = 'LF Edge Fledge Export Service'
Timeout = "5s"

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Clients]
  [Clients.edgex-core-data]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

[Trigger]
Type="edgex-messagebus"
SubscribeTopics="edgex/events/#"
PublishTopic="example"
  [Trigger.EdgexMessageBus]
  Type = "redisstreams"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    [Trigger.EdgexMessageBus.PublishHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"

[ApplicationSettings]
FledgeSouthHTTPEndpoint = "http://192.168.0.10:6683/sensor-reading"
