[Writable]
LogLevel = 'INFO'
    [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = '5m'
    MaxRetryCount = 10

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Simple CBOR Filter Application Service started'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Database]
Type = "redisdb"
Host = "localhost"
Port = 6379
Timeout = "30s"

[Clients]
    [Clients.edgex-core-data]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48080

# Choose either an HTTP trigger or MessageBus trigger

#[Trigger]
#Type="http"

[Trigger]
Type="edgex-messagebus"
SubscribeTopics="edgex/events/#"
PublishTopic="example"
  [Trigger.EdgexMessageBus]
  Type = "redisstreams"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    [Trigger.EdgexMessageBus.PublishHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"

[ApplicationSettings]
ValueDescriptors = "Image"



