[Writable]
LogLevel = 'DEBUG'
    [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = '5m'
    MaxRetryCount = 10

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a sample Application Service to receive HTTP request as trigger'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.edgex-core-data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.edgex-core-command]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48082

# This example expect custom type via HTTP Trigger
[Trigger]
Type="http"

[ApplicationSettings]
DeviceName = "Simple-Device01"
CommandName = "Switch"
