[Writable]
  LogLevel = "INFO"
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.mqtt]
        path = "mqtt"
        [Writable.InsecureSecrets.mqtt.Secrets]
            username = "edgex"
            password = "password"
            cacert = ""
            clientcert = ""
            clientkey = ""

[Service]
BootTimeout = "30s"
CheckInterval = "10s"
Host = "localhost"
ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
Port = 50002
Protocol = "http"
ReadMaxLimit = 100
StartupMsg = "App service export to InfluxDB has Started"
Timeout = "5s"

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

[Trigger]
Type="edgex-messagebus"
SubscribeTopics="edgex/events/#"
  [Trigger.EdgexMessageBus]
  Type = "redisstreams"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"

# App Service custom configuration
[MqttSecretConfig]
BrokerAddress = "tcp://localhost:1883"
ClientId = "InfluxDBExport"
AutoReconnect = true
Topic = "edgex/EdgeXEvents"
AuthMode = "usernamepassword"
SecretPath = "mqtt"
