[Writable]
LogLevel = 'INFO'
    [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = '5m'
    MaxRetryCount = 10

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a sample Filter/XML Transform Application Service'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Database]
Type = "redisdb"
Host = "localhost"
Port = 6379
Timeout = "30s"
Username = ""
Password = ""

[SecretStore]
  Host = 'localhost'
  Port = 8200
  Path = '/v1/secret/edgex/appservice/'
  Protocol = 'https'

  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
  AuthToken = 'edgex'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Trigger]
Type="edgex-messagebus"
SubscribeTopic="events"
PublishTopic="somewhere"
    [Trigger.EdgexMessageBus]
    Type = "zero"
        [Trigger.EdgexMessageBus.SubscribeHost]
        Host = "localhost"
        Port = 5563
        Protocol = "tcp"
        [Trigger.EdgexMessageBus.PublishHost]
        Host = "*"
        Port = 5565
        Protocol = "tcp"


[ApplicationSettings]
DeviceNames = "Random-Float-Device"
